# Generated by Django 5.0.6 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
