# Generated by Django 5.0.6 on 2026-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_player_user_room_is_public_room_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='multiplier_applied',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='streak_at_answer',
            field=models.IntegerField(default=0),
        ),
    ]
