# Generated by Django 5.0.6 on 2026-03-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_questionpack_customquestion_room_pack'),
        ('rooms', '0005_publictournamentconfig'),
    ]

    operations = [
    ]
