# Generated by Django 5.0.6 on 2026-03-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_merge_20260321_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_mode',
            field=models.CharField(choices=[('classic', 'Klasyczny'), ('duel', 'Pojedynek'), ('survival', 'Przetrwanie')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='publictournamentconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
