# Generated by Django 5.0.6 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_score',
            field=models.IntegerField(default=0),
        ),
    ]
