# Generated by Django 5.0.6 on 2026-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievements_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('fox', '🦊'), ('wolf', '🐺'), ('lion', '🦁'), ('tiger', '🐯'), ('bear', '🐻'), ('raccoon', '🦝'), ('frog', '🐸'), ('penguin', '🐧'), ('owl', '🦉'), ('butterfly', '🦋'), ('dragon', '🐉'), ('unicorn', '🦄'), ('octopus', '🐙'), ('shark', '🦈'), ('turtle', '🐢'), ('cat', '🐱'), ('robot', '🤖'), ('alien', '👾'), ('ninja', '🥷'), ('wizard', '🧙')], default='fox', max_length=20),
        ),
    ]
