# Generated by Django 5.0.6 on 2026-03-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_challenge'),
        ('accounts', '0005_alter_userprofile_avatar'),
    ]

    operations = [
    ]
