# Generated by Django 5.0.6 on 2026-03-21 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0002_challenge_0005_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=5, unique=True)),
                ('avatar', models.CharField(default='🛡️', max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clans',
            },
        ),
        migrations.CreateModel(
            name='ClanInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.clan')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_clan_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_clan_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clan_invites',
            },
        ),
        migrations.CreateModel(
            name='ClanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Lider'), ('officer', 'Oficer'), ('member', 'Członek')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clan_memberships',
                'unique_together': {('clan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rank', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'season_results',
                'ordering': ['final_rank'],
                'unique_together': {('season', 'user')},
            },
        ),
    ]
