# Generated by Django 5.0.6 on 2026-03-21 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_season_clan_claninvite_clanmembership_seasonresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('challenge_type', models.CharField(choices=[('play_games', 'Zagraj gier'), ('win_games', 'Wygraj gier'), ('correct_answers', 'Poprawnych odpowiedzi'), ('streak', 'Streak'), ('survival_rounds', 'Przeżyj rund')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('coin_reward', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'daily_challenges',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('profile_frame', 'Ramka profilu'), ('confetti_effect', 'Efekt confetti'), ('title', 'Tytuł')], max_length=20)),
                ('price', models.IntegerField()),
                ('emoji_icon', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shop_items',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='accounts.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_challenge_progress',
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='accounts.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_items',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
